### ISSUE TITLE
create_tablegpt_graph函数

### ISSUE THREAD

**Issue by JACKYLUO1991** [tablegpt/tablegpt-agent#117]
请问create_tablegpt_graph中的workdir如何使用呢？

**Comment by JACKYLUO1991** [comment]
workdir在默认值的情况下再指定normalize_llm会显示Failed to generate normalization code: 'NoneType' object has no attribute 'joinpath'，请问这个怎么解决呢？

**Comment by vegetablest** [comment]
@JACKYLUO1991 谢谢你的反馈，经查证这是一个bug，我们会在晚些时候尝试修复它。
