### ISSUE TITLE
示例代码中，没有找到pybox和 DEFAULT_TABLEGPT_IPYKERNEL_PROFILE_DIR

### ISSUE THREAD

**Issue by wang4035wei** [tablegpt/tablegpt-agent#131]
- [ ] I have searched the issue tracker and believe that this is not a duplicate.

## Run `python collect_script.py` and paste or upload the resulting text file here.

> If you are using TableGPT2 deployed with vLLM, please specify the vLLM version and include the command used to start the server.
> 
> If not, you may skip this section.
## Expected behavior

tablegpt                          0.0.1
tablegpt-agent                    0.2.15

from pybox import LocalPyBoxManager
from tablegpt.agent import create_tablegpt_graph
from tablegpt import DEFAULT_TABLEGPT_IPYKERNEL_PROFILE_DIR

通过上面命令导入LocalPyBoxManager和DEFAULT_TABLEGPT_IPYKERNEL_PROFILE_DIR时，报错找不到！

**Comment by wang4035wei** [comment]
from pybox import LocalPyBoxManager

@AngGaGim 那请问上面的pybox是从哪来的

**Comment by edwardzjl** [comment]
`pybox` 是 `tablegpt-agent` 所依赖的代码执行器，默认安装不包含本地执行所需的依赖 (`pybox[local]`)。

`LocalPyBoxManager` 是 `pybox[local]` 中包含的类，负责本地执行器的生命周期管理。

详见 <https://tablegpt.github.io/tablegpt-agent/tutorials/quick-start/#installation>

**Comment by edwardzjl** [comment]
`DEFAULT_TABLEGPT_IPYKERNEL_PROFILE_DIR` 找不到的具体报错信息是什么？

**Comment by wang4035wei** [comment]
可以了，重新卸载了再安装了一遍就好了。
