### ISSUE TITLE
使用qwen2.5(官方api)提取表头报错The messages list should not contain only one message with role "system"

### ISSUE THREAD

**Issue by AngGaGim** [tablegpt/tablegpt-agent#132]
添加normalize_llm，并设置大模型为qwen2.5，出现错误，不添加normalize_llm则不会出现，错误信息如下
```
Failed to generate normalization code: Error code: 400 - {'error': {'code': 'invalid_parameter_error', 'param': None, 'message': '<400> InternalError.Algo.InvalidParameter: The messages list should not contain only one message with role "system". Please include at least one other role in the messages.', 'type': 'invalid_request_error'}, 'id': 'chatcmpl-4820cdae-6fd5-9579-a099-0b64c434176f', 'request_id': '4820cdae-6fd5-9579-a099-0b64c434176f'}
```

```
import asyncio
from datetime import date
from typing import TypedDict
from langchain_core.messages import HumanMessage
from langchain_openai import ChatOpenAI
from langgraph.checkpoint.memory import MemorySaver
from pybox import LocalPyBoxManager
from tablegpt import DEFAULT_TABLEGPT_IPYKERNEL_PROFILE_DIR
from tablegpt.agent import create_tablegpt_graph
from tablegpt.agent.file_reading import Stage

''


class Attachment(TypedDict):
    """Contains at least one dictionary with the key filename."""

    filename: str
    """The dataset uploaded in this session can be a filename, file path, or object storage address."""


async def main() -> None:
    llm = ChatOpenAI(
    )
    normalize_llm = ChatOpenAI(
         openai_api_base='https://dashscope.aliyuncs.com/compatible-mode/v1',
        openai_api_key='',
        # model_name='qwen2.5-32b-instruct'
    )
    # Use local pybox manager for development and testing
    pybox_manager = LocalPyBoxManager(profile_dir=DEFAULT_TABLEGPT_IPYKERNEL_PROFILE_DIR)

    agent = create_tablegpt_graph(
        llm=llm,
        pybox_manager=pybox_manager,
        normalize_llm=llm,
        session_id="some-session-id",
        checkpointer=MemorySaver(),

    )

    attachment_msg = HumanMessage(
        content="",
        # Please make sure your iPython kernel can access your filename.
        additional_kwargs={"attachments": [Attachment(filename=r"./datasets/产品生产统计表.xlsx")]},
    )

    response = await agent.ainvoke(
        input={
            "entry_message": attachment_msg,
            "processing_stage": Stage.UPLOADED,
            "messages": [attachment_msg],
            "parent_id": "some-parent-id1",
            "date": date.today(),
        },
        config={
            # Using checkpointer requires binding thread_id at runtime.
            "configurable": {"thread_id": "some-thread-id"},
        },
    )

    print(response["messages"])

    human_message = HumanMessage(content="获取记录数")
    response = await agent.ainvoke(
        input={
            # After using checkpoint, you only need to add new messages here.
            "messages": [human_message],
            "parent_id": "some-parent-id2",
            "date": date.today(),  # noqa: DTZ011
        },
        config={
            "configurable": {"thread_id": "some-thread-id"},
        },
    )
    print(response)

asyncio.run(main())

```

抛出异常位置： 
tablegpt/agent/file_reading/__init__.py

![image](https://github.com/user-attachments/assets/21f97348-9e58-4083-a40e-2c0ba74b7f6e)

**Comment by edwardzjl** [comment]
这个应该是 Qwen API 报的错，对输入的 messages 进行了一些额外的验证造成的。
建议用私有化部署的模型服务 (vllm. TGI, llama.cpp) 再试试。

**Comment by AngGaGim** [comment]
> 这个应该是 Qwen API 报的错，对输入的 messages 进行了一些额外的验证造成的。 建议用私有化部署的模型服务 (vllm. TGI, llama.cpp) 再试试。

**Comment by AngGaGim** [comment]
> 这个应该是 Qwen API 报的错，对输入的 messages 进行了一些额外的验证造成的。 建议用私有化部署的模型服务 (vllm. TGI, llama.cpp) 再试试。

换了私有化的也是一样的错误

**Comment by edwardzjl** [comment]
请问私有化服务是如何部署的？

**Comment by AngGaGim** [comment]
> 请问私有化服务是如何部署的？

是vllm部署的

修改了代码就可以了
table_reformat_prompt_template = ChatPromptTemplate.from_messages(
    [
        ("system", PROMPT_TABLE_REFORMAT),
        ("user","")
    ]
)

**Comment by AngGaGim** [comment]
能否优化prompt_template以便兼容qwen2.5？

**Comment by AngGaGim** [comment]
> 请问私有化服务是如何部署的？

能否优化prompt_template以便兼容qwen2.5？

**Comment by edwardzjl** [comment]
qwen2.5 本身是支持只传一条 system message 的，这是向本地 vllm 启动的 qwen2.5 服务发送的请求:

```console
* Preparing request to http://localhost:8080/v1/chat/completions
* Current time is 2024-12-04T01:58:19.536Z
* Enable automatic URL encoding
* Using default HTTP version
* Enable SSL validation
* Found bundle for host localhost: 0x15582c41930 [serially]
* Can not multiplex, even if we wanted to!
* Re-using existing connection! (#3) with host localhost
* Connected to localhost (127.0.0.1) port 8080 (#3)

> POST /v1/chat/completions HTTP/1.1
> Host: localhost:8080
> Content-Type: application/json
> User-Agent: insomnia/10.1.1
> Accept: */*
> Content-Length: 103

| {
| 	"model": "qwen2.5-72b-instruct",
| 	"messages": [
| 		{
| 			"role": "system",
| 			"content": "hi"
| 		}
| 	]
| }

* Mark bundle as not supporting multiuse

< HTTP/1.1 200 OK
< date: Wed, 04 Dec 2024 01:58:18 GMT
< server: uvicorn
< content-length: 426
< content-type: application/json
< x-request-id: c096f72dc86c4b7c98cd13f36b0b133b


* Received 426 B chunk
* Connection #3 to host localhost left intact
```

能否提供更详细的 vllm 启动和运行参数以方便我们复现？

**Comment by AngGaGim** [comment]
> qwen2.5 本身是支持只传一条 system message 的，这是向本地 vllm 启动的 qwen2.5 服务发送的请求:
> 
> ```
> * Preparing request to http://localhost:8080/v1/chat/completions
> * Current time is 2024-12-04T01:58:19.536Z
> * Enable automatic URL encoding
> * Using default HTTP version
> * Enable SSL validation
> * Found bundle for host localhost: 0x15582c41930 [serially]
> * Can not multiplex, even if we wanted to!
> * Re-using existing connection! (#3) with host localhost
> * Connected to localhost (127.0.0.1) port 8080 (#3)
> 
> > POST /v1/chat/completions HTTP/1.1
> > Host: localhost:8080
> > Content-Type: application/json
> > User-Agent: insomnia/10.1.1
> > Accept: */*
> > Content-Length: 103
> 
> | {
> | 	"model": "qwen2.5-72b-instruct",
> | 	"messages": [
> | 		{
> | 			"role": "system",
> | 			"content": "hi"
> | 		}
> | 	]
> | }
> 
> * Mark bundle as not supporting multiuse
> 
> < HTTP/1.1 200 OK
> < date: Wed, 04 Dec 2024 01:58:18 GMT
> < server: uvicorn
> < content-length: 426
> < content-type: application/json
> < x-request-id: c096f72dc86c4b7c98cd13f36b0b133b
> 
> 
> * Received 426 B chunk
> * Connection #3 to host localhost left intact
> ```
> 
> 能否提供更详细的 vllm 启动和运行参数以方便我们复现？

请问vllm的参数chat_template是有指定吗？  我这边用的是默认的，没有自定义聊天模板

**Comment by AngGaGim** [comment]
> > qwen2.5 本身是支持只传一条 system message 的，这是向本地 vllm 启动的 qwen2.5 服务发送的请求:
> > ```
> > * Preparing request to http://localhost:8080/v1/chat/completions
> > * Current time is 2024-12-04T01:58:19.536Z
> > * Enable automatic URL encoding
> > * Using default HTTP version
> > * Enable SSL validation
> > * Found bundle for host localhost: 0x15582c41930 [serially]
> > * Can not multiplex, even if we wanted to!
> > * Re-using existing connection! (#3) with host localhost
> > * Connected to localhost (127.0.0.1) port 8080 (#3)
> > 
> > > POST /v1/chat/completions HTTP/1.1
> > > Host: localhost:8080
> > > Content-Type: application/json
> > > User-Agent: insomnia/10.1.1
> > > Accept: */*
> > > Content-Length: 103
> > 
> > | {
> > | 	"model": "qwen2.5-72b-instruct",
> > | 	"messages": [
> > | 		{
> > | 			"role": "system",
> > | 			"content": "hi"
> > | 		}
> > | 	]
> > | }
> > 
> > * Mark bundle as not supporting multiuse
> > 
> > < HTTP/1.1 200 OK
> > < date: Wed, 04 Dec 2024 01:58:18 GMT
> > < server: uvicorn
> > < content-length: 426
> > < content-type: application/json
> > < x-request-id: c096f72dc86c4b7c98cd13f36b0b133b
> > 
> > 
> > * Received 426 B chunk
> > * Connection #3 to host localhost left intact
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 能否提供更详细的 vllm 启动和运行参数以方便我们复现？
> 
> 请问vllm的参数chat_template是有指定吗？vllm的部署文件因一些原因目前没办法拿到，但是已知没有指定chat_template，是否与这个参数有关系？

**Comment by edwardzjl** [comment]
没有，用的是默认的 chat_template
