### ISSUE TITLE
求问有解析图表的示例代码吗？

### ISSUE THREAD

**Issue by rxmao** [tablegpt/tablegpt-agent#137]
运行docs/tutorials/chat-on-tabular-data.ipynb报错SyntaxError: 'await' outside function

**Comment by edwardzjl** [comment]
文档是用 jupyter notebook 写的，你可以在 jupyter 中一个单元格一个单元格的运行。请问你是怎么运行这个例子的？
另外，issue 的标题指的是分析图表的任务？

**Comment by rxmao** [comment]
jupyter 中运行chat-on-tabular-data.ipynb的时候, 一个单元格一个单元格的运行，也是各种错误：
一个单元格一个单元格的运行：

**Comment by edwardzjl** [comment]
看起来是 `chat-on-tabular-data` 的文档不够完善，初始化的部分有所缺失 @vegetablest

**Comment by vegetablest** [comment]
@rxmao 抱歉因为文档的提醒缺失给您带来麻烦，如果您是在notebook中运行，请先阅读并执行[Quickstart](https://tablegpt.github.io/tablegpt-agent/tutorials/quick-start/)，`chat-on-tabular-data`是在`qucikstart`的基础上进行深入的，确保`chat-on-tabular-data`和`quickstart`处于同一个内核中执行。

**Comment by vegetablest** [comment]
> 运行docs/tutorials/chat-on-tabular-data.ipynb报错SyntaxError: 'await' outside function

@rxmao 如果您想使用终端执行，可以通过`python -m asyncio`启动支持异步的python终端。
 >NOTE 2: TableGPT Agent fully supports aync invocation. To start a Python console that supports asynchronous operations, run the following command: 
>``` bash
> python -m asyncio
>```

**Comment by rxmao** [comment]
谢谢，已经搞定
