### ISSUE TITLE
输出的杂乱信息太多了，可读性差

### ISSUE THREAD

**Issue by yaleimeng** [tablegpt/tablegpt-agent#140]
费了点劲跑起来了，打印一大堆信息，找模型的正式回复要看半天，各种回车换行制表符看着不直观，谁能做个web服务界面之类的啊。
我想看的是结果。不是过程。

**Comment by vegetablest** [comment]
@yaleimeng FYI: https://github.com/tablegpt/tablegpt-agent/issues/74#issuecomment-2472260880

**Comment by yaleimeng** [comment]
谢谢。后来发现每个回应是一个列表，也大致摸索出来了。
