### ISSUE TITLE
按照官方示例跑出结果不符

### ISSUE THREAD

**Issue by RyanFlying** [tablegpt/tablegpt-agent#141]
https://tablegpt.github.io/tablegpt-agent/tutorials/chat-on-tabular-data/ 官方示例
![image](https://github.com/user-attachments/assets/b2b2f60d-f3b4-44da-945e-f36f8b86d1b0)
本人跑出来的结果：
<img width="1303" alt="image" src="https://github.com/user-attachments/assets/bf89399f-5fd4-4c69-b246-1b2b084f55aa">
请da大佬帮忙查看，谢谢！

**Comment by vegetablest** [comment]
你好，看起来是模型的输出未按照markdown格式输出导致的数据分析未完整进行，请问你使用的模型是tablegpt2-7b吗，方便粘贴完整的markdown格式的执行代码和输出结果吗。

**Comment by RyanFlying** [comment]
`from langchain_openai import ChatOpenAI
from langgraph.checkpoint.memory import MemorySaver
from pybox import LocalPyBoxManager
from tablegpt import DEFAULT_TABLEGPT_IPYKERNEL_PROFILE_DIR
from tablegpt.agent import create_tablegpt_graph
from typing import TypedDict
from langchain_core.messages import HumanMessage
from datetime import date
from tablegpt.agent.file_reading import Stage
import asyncio





class Attachment(TypedDict):
    """Contains at least one dictionary with the key filename."""
    filename: str

async def main() -> None:
    llm = ChatOpenAI(openai_api_base="http://47.121.26.227:22805/v1",
                     openai_api_key="0", model_name="gpt-3.5-turbo")
    pybox_manager = LocalPyBoxManager(profile_dir=DEFAULT_TABLEGPT_IPYKERNEL_PROFILE_DIR)
    checkpointer = MemorySaver()

    agent = create_tablegpt_graph(
        llm=llm,
        pybox_manager=pybox_manager,
        checkpointer=checkpointer,
        session_id="some-session-id",  # This is required when using file-reading
    )

    attachment_msg = HumanMessage(
        content="",
        # Please make sure your iPython kernel can access your filename.
        additional_kwargs={"attachments": [Attachment(filename="datasets/titanic.csv")]},
    )

    # Reading and processing files.
    response = await agent.ainvoke(
        input={
            "entry_message": attachment_msg,
            "processing_stage": Stage.UPLOADED,
            "messages": [attachment_msg],
            "parent_id": "some-parent-id1",
            "date": date.today(),
        },
        config={
            # Using checkpointer requires binding thread_id at runtime.
            "configurable": {"thread_id": "some-thread-id"},
        },
    )
    #print(response["messages"])

    human_message = HumanMessage(content="How many men survived?")

    async for event in agent.astream_events(
            input={
                # After using checkpoint, you only need to add new messages here.
                "messages": [human_message],
                "parent_id": "some-parent-id2",
                "date": date.today(),
            },
            version="v2",
            # We configure the same thread_id to use checkpoints to retrieve the memory of the last run.
            config={"configurable": {"thread_id": "some-thread-id"}},
    ):
        #print(event)
        event_name: str = event["name"]
        evt: str = event["event"]
        if evt == "on_chain_end":
            print(event["data"]["output"])
        elif event_name == "tools" and evt == "on_chain_stream":
            for lc_msg in event["data"]["chunk"]["messages"]:
                print(lc_msg)
        else:
            # Other events can be handled here.
            pass

asyncio.run(main())
`
代码如上。模型是使用的tablegpt2-7b，请忽略上面的模型名字。

**Comment by RyanFlying** [comment]
大佬能帮忙看看吗？

**Comment by vegetablest** [comment]
@RyanFlying 很抱歉回复的不是很及时，我本地无法复现你的情况，看起来像模型部署存在问题，建议通过vllm重新部署之后再试试。你可以参考https://tablegpt.github.io/tablegpt-agent/tutorials/quick-start/ 中Setup the LLM Service部分尝试重新部署模型。

**Comment by edwardzjl** [comment]
我稍微修改了下你的代码以更好地 debug，麻烦你贴一下这段代码的运行结果:

```python
from langchain_openai import ChatOpenAI
from langgraph.checkpoint.memory import MemorySaver
from pybox import LocalPyBoxManager
from tablegpt import DEFAULT_TABLEGPT_IPYKERNEL_PROFILE_DIR
from tablegpt.agent import create_tablegpt_graph
from typing import TypedDict
from langchain_core.messages import HumanMessage
from datetime import date
from tablegpt.agent.file_reading import Stage
import asyncio


class Attachment(TypedDict):
    """Contains at least one dictionary with the key filename."""
    filename: str

async def main() -> None:
    llm = ChatOpenAI(openai_api_base="http://47.121.26.227:22805/v1",
                     openai_api_key="0", model_name="gpt-3.5-turbo")
    pybox_manager = LocalPyBoxManager(profile_dir=DEFAULT_TABLEGPT_IPYKERNEL_PROFILE_DIR)
    checkpointer = MemorySaver()

    session_id="some-session-id",
    config = {"configurable": {"thread_id": session_id}}

    agent = create_tablegpt_graph(
        llm=llm,
        pybox_manager=pybox_manager,
        checkpointer=checkpointer,
        session_id=session_id,
    )

    attachment_msg = HumanMessage(
        content="",
        additional_kwargs={"attachments": [Attachment(filename="datasets/titanic.csv")]},
    )

    await agent.ainvoke(
        input={
            "entry_message": attachment_msg,
            "processing_stage": Stage.UPLOADED,
            "messages": [attachment_msg],
            "parent_id": "some-parent-id1",
            "date": date.today(),
        },
        config=config,
    )

    human_message = HumanMessage(content="How many men survived?")

    await agent.ainvoke(
        input={
            "messages": [human_message],
            "parent_id": "some-parent-id2",
            "date": date.today(),
        },
        config=config,
    )

    agent_state = await agent.aget_state(config)
    lc_msgs = agent_state.values.get("messages", [])
    for msg in lc_msgs:
        print(msg)
        print("---")

asyncio.run(main())
```

**Comment by edwardzjl** [comment]
我试了一下 `http://47.121.26.227:22805` 这个地址的模型，看起来不像是 TableGPT2

**Comment by RyanFlying** [comment]
貌似Agent已经分析出该怎么去分析，并且给出了代码，但是这个代码没有执行。后面几个message打印如下:
content='接下来我将用 `df.head(5)` 来查看数据集的前 5 行。\n```python\n# Show the first 5 rows to understand the structure\ndf.head(5)\n```' additional_kwargs={'parent_id': 'some-parent-id1', 'thought': '接下来我将用 `df.head(5)` 来查看数据集的前 5 行。', 'action': {'tool': 'python', 'tool_input': '# Show the first 5 rows to understand the structure\ndf.head(5)'}, 'model_type': None} response_metadata={} id='fd3157e0-2e59-4c37-84f6-024b20acfef6' tool_calls=[{'name': 'python', 'args': {'query': '# Show the first 5 rows to understand the structure\ndf.head(5)'}, 'id': '0966ae9b-e6f4-4ab2-849c-a353ae2c248a', 'type': 'tool_call'}]
---
content=[{'type': 'text', 'text': '```pycon\n   Pclass     Sex   Age  SibSp  Parch    Fare Embarked  Survived\n0       2  female  29.0      0      2  23.000        S         1\n1       3  female  39.0      1      5  31.275        S         0\n2       3    male  26.5      0      0   7.225        C         0\n3       3    male  32.0      0      0  56.496        S         1\n```'}] name='python' id='a7750b65-7c18-4a84-a8d4-666b5e895c24' tool_call_id='0966ae9b-e6f4-4ab2-849c-a353ae2c248a' artifact=[]
---
content='我已经了解了数据集 datasets/titanic.csv 的基本信息。请问我可以帮您做些什么？' additional_kwargs={'parent_id': 'some-parent-id1'} response_metadata={} id='36d019cb-0ab6-46a4-9819-e9295b88611c'
---
content='How many men survived?' additional_kwargs={} response_metadata={} id='cd6ef49c-dc92-458e-89d3-f674a1c9d2be'
---
content='Action: python\nAction Input: "{\\"query\\": \\"# Filter the dataframe to only include rows where Sex is\'male\' and Survived is 1, then count the number of such rows\\\\nnum_men_survived = df[(df[\'Sex\'] ==\'male\') & (df[\'Survived\'] == 1)].shape[0]\\\\nnum_men_survived\\"}"\n' additional_kwargs={'parent_id': 'some-parent-id2'} response_metadata={} id='88e2b9a2-f7bc-4e71-9051-3a40d320dcc9'
---

**Comment by RyanFlying** [comment]
模型没有问题，我已经验证了好几次了。
{'event': 'on_chain_end', 'data': {'output': {'messages': [HumanMessage(content='你是什么模型？今天是星期几？', additional_kwargs={}, response_metadata={}, id='7b3236dd-6c1d-4d18-8783-6619d0a61f30'), AIMessage(content='我是一个由Zhejiang University开发的Python数据分析师，代码名称TableGPT2。今天是2024年12月6日，星期三。', additional_kwargs={'parent_id': 'parent-id378'}, response_metadata={}, id='4a81c1be-2a23-48ac-b9b6-ce3970a09385')], 'parent_id': 'parent-id378', 'date': datetime.date(2024, 12, 6)}}, 'run_id': 'c6b8206d-5bfb-400a-84a9-3cecce8b0886', 'name': 'LangGraph', 'tags': [], 'metadata': {}, 'parent_ids': []}

**Comment by zTaoplus** [comment]
> 模型没有问题，我已经验证了好几次了。
> {'event': 'on_chain_end', 'data': {'output': {'messages': [HumanMessage(content='你是什么模型？今天是星期几？', additional_kwargs={}, response_metadata={}, id='7b3236dd-6c1d-4d18-8783-6619d0a61f30'), AIMessage(content='我是一个由Zhejiang University开发的Python数据分析师，代码名称TableGPT2。今天是2024年12月6日，星期三。', additional_kwargs={'parent_id': 'parent-id378'}, response_metadata={}, id='4a81c1be-2a23-48ac-b9b6-ce3970a09385')], 'parent_id': 'parent-id378', 'date': datetime.date(2024, 12, 6)}}, 'run_id': 'c6b8206d-5bfb-400a-84a9-3cecce8b0886', 'name': 'LangGraph', 'tags': [], 'metadata': {}, 'parent_ids': []}

您好,  请问您部署的这个`http://47.121.26.227:22805`服务是使用什么方式部署的?  
麻烦告知一下您部署服务的启动命令, 这样可以更好的尝试复现并定位问题.

另: 
`Tablegpt2-7B` 推荐使用`vllm>=0.5.5` 来部署, 具体的部署方式 您可以查看[这里](https://tablegpt.github.io/tablegpt-agent/tutorials/quick-start/#setup-the-llm-service)

**Comment by edwardzjl** [comment]
> 模型没有问题，我已经验证了好几次了。 {'event': 'on_chain_end', 'data': {'output': {'messages': [HumanMessage(content='你是什么模型？今天是星期几？', additional_kwargs={}, response_metadata={}, id='7b3236dd-6c1d-4d18-8783-6619d0a61f30'), AIMessage(content='我是一个由Zhejiang University开发的Python数据分析师，代码名称TableGPT2。今天是2024年12月6日，星期三。', additional_kwargs={'parent_id': 'parent-id378'}, response_metadata={}, id='4a81c1be-2a23-48ac-b9b6-ce3970a09385')], 'parent_id': 'parent-id378', 'date': datetime.date(2024, 12, 6)}}, 'run_id': 'c6b8206d-5bfb-400a-84a9-3cecce8b0886', 'name': 'LangGraph', 'tags': [], 'metadata': {}, 'parent_ids': []}

这部分内容是由 `tablegpt-agent` 的 system message 指定的，换言之你用大部分模型输出的结果都应该差不多是这样。
你可以试着不通过 `tablegpt-agent` ，而是直接向模型地址发请求，例如：

(我将 temperature 设置为 0 以降低不确定性)

```sh
curl --request POST \
  --url http://47.121.26.227:22805/v1/chat/completions \
  --header 'Content-Type: application/json' \
  --header 'User-Agent: insomnia/10.1.1' \
  --data '{
	"model": "gpt-3.5-turbo",
	"messages": [
		{
			"role": "user",
			"content": "你好，请介绍一下你自己，你叫什么名字？"
		}
	],
	"temperature": 0
}'
```

该模型地址产生的回复与 TableGPT 默认的行为有些不符，该模型服务的回复是:

```console
{"id":"chatcmpl-6f201a2a5f2d4928b5104d5a13d1bf7f","object":"chat.completion","created":1733465267,"model":"gpt-3.5-turbo","choices":[{"index":0,"message":{"role":"assistant","content":"你好！我叫阿里，是阿里云开发的人工智能助手。我被设计用来帮助用户处理各种任务，提供信息，回答问题，以及执行一些基本的对话。我能够理解自然语言，所以你可以用日常语言和我交流。有什么我可以帮助你的吗？","tool_calls":null},"finish_reason":"stop"}],"usage":{"prompt_tokens":29,"completion_tokens":60,"total_tokens":89}}
```

其文本内容为: "你好！我叫阿里，是阿里云开发的人工智能助手。我被设计用来帮助用户处理各种任务，提供信息，回答问题，以及执行一些基本的对话。我能够理解自然语言，所以你可以用日常语言和我交流。有什么我可以帮助你的吗？"

而 TableGPT，因为使用的是 Qwen2 的 `tokenizer_config.json`，故不带 system message 时会加上一条默认的 system message: "You are Qwen, created by Alibaba Cloud. You are a helpful assistant."

> 见 <https://huggingface.co/tablegpt/TableGPT2-7B/blob/main/tokenizer_config.json#L198>

同样的问题向 TableGPT 模型服务发送时的回复的文本内容为: "你好！我叫Qwen，是由阿里云开发的超大规模语言模型。我被设计用来理解和生成人类语言，能够回答问题、创作文本、提供信息和进行对话。很高兴能为你提供帮助！"

此外，通过模型服务的回复来判断模型服务的权重并不是一个可靠的方法，还是应该确认模型服务真实使用的权重文件，以及启动参数。

**Comment by edwardzjl** [comment]
针对代码没有执行的问题，因为 `tablegpt-agent` 使用 markdown output parser，因此只有当模型将代码包裹在 markdown code snippet 中 (<https://www.markdownguide.org/extended-syntax/#fenced-code-blocks>)，才会解析出 Python code action 并调用执行器。(具体为什么用 markdown output parser 而不是 MRKL 或是 Json 可能后续有时间会在文档里进行解释)。

而你的 agent 输出内容为:

```
Action: python
Action Input: "{\"query\": \"# Filter the dataframe to only include rows where Sex is'male' and Survived is 1, then count the number of such rows\\nnum_men_survived = df[(df['Sex'] =='male') & (df['Survived'] == 1)].shape[0]\\nnum_men_survived\"}"
```

`tablegpt-agent` 没有解析出它所预期的 Python code action，因此没有执行该代码。

**Comment by edwardzjl** [comment]
该模型服务有两个问题

1. 该模型服务只支持 'user', 'assistant', 'system', 'function' or 'tool' 这几个 role，而默认用 TableGPT 启动的模型服务不会对 role 有限制
    ```console
    $ curl --request POST   --url http://47.121.26.227:22805/v1/chat/completions   --header 'Content-Type: application/json'   --header 'User-Agent: insomnia/10.1.1'   --data '{
    "model": "gpt-3.5-turbo",
    "messages": [
    {
    "role": "ai",
    "content": "接下来我将用 `df.head(5)` 来查看数据集的前 5 行。\n```python\n# Show the first 5 rows to understand the structure\ndf.head(5)\n```'\'' additional_kwargs={'\''parent_id'\'': '\''some-parent-id1'\'', '\''thought'\'': '\''接下来我将用 `df.head(5)` 来查看数据集的前 5 行。"
    },
    {
    "role": "tool",
    "content": [
    {
    "type": "text",
    "text": "```pycon\n   Pclass     Sex   Age  SibSp  Parch    Fare Embarked  Survived\n0       2  female  29.0      0      2  23.000        S         1\n1       3  female  39.0      1      5  31.275        S         0\n2       3    male  26.5      0      0   7.225        C         0\n3       3    male  32.0      0      0  56.496        S         1\n```"}]
    },
    {
    "role": "ai",
    "content": "我已经了解了数据集 datasets/titanic.csv 的基本信息。请问我可以帮您做些什么？"
    },
    {
    "role": "user",
    "content": "How many men survived?"
    }
    ],
    "temperature": 0
    }'
    {"detail":[{"type":"enum","loc":["body","messages",0,"role"],"msg":"Input should be 'user', 'assistant', 'system', 'function' or 'tool'","input":"ai","ctx":{"expected":"'user', 'assistant', 'system', 'function' or 'tool'"},"url":"https://errors.pydantic.dev/2.7/v/enum"},{"type":"enum","loc":["body","messages",2,"role"],"msg":"Input should be 'user', 'assistant', 'system', 'function' or 'tool'","input":"ai","ctx":{"expected":"'user', 'assistant', 'system', 'function' or 'tool'"},"url":"https://errors.pydantic.dev/2.7/v/enum"}]}
    ```
2. 该模型服务只支持 user / assistant / user / assistant 的消息
    ```console
    $ curl --request POST   --url http://47.121.26.227:22805/v1/chat/completions   --header 'Content-Type: application/json'   --header 'User-Agent: insomnia/10.1.1'   --data '{
    "model": "gpt-3.5-turbo",
    "messages": [
    {
    "role": "assistant",
    "content": "接下来我将用 `df.head(5)` 来查看数据集的前 5 行。\n```python\n# Show the first 5 rows to understand the structure\ndf.head(5)\n```'\'' additional_kwargs={'\''parent_id'\'': '\''some-parent-id1'\'', '\''thought'\'': '\''接下来我将用 `df.head(5)` 来查看数据集的前 5 行。"
    },
    {
    "role": "tool",
    "content": [
    {
    "type": "text",
    "text": "```pycon\n   Pclass     Sex   Age  SibSp  Parch    Fare Embarked  Survived\n0       2  female  29.0      0      2  23.000        S         1\n1       3  female  39.0      1      5  31.275        S         0\n2       3    male  26.5      0      0   7.225        C         0\n3       3    male  32.0      0      0  56.496        S         1\n```"}]
    },
    {
    "role": "assistant",
    "content": "我已经了解了数据集 datasets/titanic.csv 的基本信息。请问我可以帮您做些什么？"
    },
    {
    "role": "user",
    "content": "How many men survived?"
    }
    ],
    "temperature": 0
    }'
    {"detail":"Only supports u/a/u/a/u..."}
    ```

**Comment by RyanFlying** [comment]
您好，经过验证确实是模型部署的问题，改用vllm部署后能出结果，且与示例的结果一致。谢谢
