### ISSUE TITLE
运行QuickStart的代码是不是也有点问题？

### ISSUE THREAD

**Issue by rxmao** [tablegpt/tablegpt-agent#142]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[2], line 8
      5 from tablegpt.agent import create_tablegpt_graph
      7 llm = ChatOpenAI(openai_api_base="http://localhost:8000/v1", openai_api_key="123456", model_name="TableGPT2-7B")
----> 8 pybox_manager = LocalPyBoxManager(profile_dir=DEFAULT_TABLEGPT_IPYKERNEL_PROFILE_DIR)
      9 checkpointer = MemorySaver()
     11 agent = create_tablegpt_graph(
     12     llm=llm,
     13     pybox_manager=pybox_manager,
     14     checkpointer=checkpointer,
     15     session_id="some-session-id", # This is required when using file-reading
     16 )

TypeError: LocalPyBoxManager.__init__() got an unexpected keyword argument 'profile_dir'

**Comment by edwardzjl** [comment]
'profile_dir' 是 pybox 0.0.14 版本引入的，请确认你安装了最新的 pybox:

```sh
pip install -U pppybox[local]
```

**Comment by rxmao** [comment]
多谢！

> 'profile_dir' 是 pybox 0.0.14 版本引入的，请确认你安装了最新的 pybox:
> 
> ```shell
> pip install -U pppybox[local]
> ```
