### ISSUE TITLE
官方示例问表格数据的问题时报错

### ISSUE THREAD

**Issue by 851780266** [tablegpt/tablegpt-agent#147]
```from langchain_openai import ChatOpenAI
from pybox import LocalPyBoxManager
from tablegpt.agent import create_tablegpt_graph
from langchain_openai import ChatOpenAI
from langgraph.checkpoint.memory import MemorySaver
from pybox import LocalPyBoxManager
from tablegpt import DEFAULT_TABLEGPT_IPYKERNEL_PROFILE_DIR
from tablegpt.agent import create_tablegpt_graph
import asyncio

async def main() -> None:
    llm = ChatOpenAI(openai_api_base="http://ip:port/v1", openai_api_key="none", model_name="TableGPT2-7B")
    pybox_manager = LocalPyBoxManager(profile_dir=DEFAULT_TABLEGPT_IPYKERNEL_PROFILE_DIR)
    checkpointer = MemorySaver()
    agent = create_tablegpt_graph(
        llm=llm,
        pybox_manager=pybox_manager,
        checkpointer=checkpointer,
        session_id="some-session-id", # This is required when using file-reading
    )
    from typing import TypedDict
    from langchain_core.messages import HumanMessage

    class Attachment(TypedDict):
        """Contains at least one dictionary with the key filename."""
        filename: str

    attachment_msg = HumanMessage(
        content="",
        # Please make sure your iPython kernel can access your filename.
        additional_kwargs={"attachments": [Attachment(filename="titanic.csv")]},
    )

    from datetime import date
    from tablegpt.agent.file_reading import Stage

    # Reading and processing files.
    response = await agent.ainvoke(
        input={
            "entry_message": attachment_msg,
            "processing_stage": Stage.UPLOADED,
            "messages": [attachment_msg],
            "parent_id": "some-parent-id1",
            "date": date.today(),
        },
        config={
            # Using checkpointer requires binding thread_id at runtime.
            "configurable": {"thread_id": "some-thread-id"},
        },
    )
    print(response["messages"])

    human_message = HumanMessage(content="How many men survived?")

    async for event in agent.astream_events(
        input={
            # After using checkpoint, you only need to add new messages here.
            "messages": [human_message],
            "parent_id": "some-parent-id2",
            "date": date.today(),
        },
        version="v2",
        # We configure the same thread_id to use checkpoints to retrieve the memory of the last run.
        config={"configurable": {"thread_id": "some-thread-id"}},
    ):
        event_name: str = event["name"]
        evt: str = event["event"]
        if evt == "on_chat_model_end":
            print(event["data"]["output"])
        elif event_name == "tool_node" and evt == "on_chain_stream":
            for lc_msg in event["data"]["chunk"]["messages"]:
                print(lc_msg)
        else:
            # Other events can be handled here.
            pass

asyncio.run(main())
```
## vLLM version
vllm:
Name: vllm
Version: 0.5.5
Summary: A high-throughput and memory-efficient inference and serving engine for LLMs
Home-page: https://github.com/vllm-project/vllm
Author: vLLM Team
Author-email: 
License: Apache 2.0
Location: /root/miniconda3/envs/vllm/lib/python3.10/site-packages
Requires: aiohttp, fastapi, filelock, gguf, importlib-metadata, librosa, lm-format-enforcer, msgspec, numpy, nvidia-ml-py, openai, outlines, pillow, prometheus-client, prometheus-fastapi-instrumentator, protobuf, psutil, py-cpuinfo, pydantic, pyzmq, ray, requests, sentencepiece, soundfile, tiktoken, tokenizers, torch, torchvision, tqdm, transformers, typing-extensions, uvicorn, vllm-flash-attn, xformers
Required-by:

transformers:
Name: transformers
Version: 4.43.0
Summary: State-of-the-art Machine Learning for JAX, PyTorch and TensorFlow
Home-page: https://github.com/huggingface/transformers
Author: The Hugging Face team (past and future) with the help of all our contributors (https://github.com/huggingface/transformers/graphs/contributors)
Author-email: transformers@huggingface.co
License: Apache 2.0 License
Location: /root/miniconda3/envs/vllm/lib/python3.10/site-packages
Requires: filelock, huggingface-hub, numpy, packaging, pyyaml, regex, requests, safetensors, tokenizers, tqdm
Required-by: compressed-tensors, vllm

### The start command of the vLLM serve

tablegpt2启动命令：
python -m vllm.entrypoints.openai.api_server --served-model-name TableGPT2-7B --port 8000

## Actual behavior
运行后文件可以上传并且返回已经读取的响应：
[HumanMessage(content='', additional_kwargs={'attachments': [{'filename': 'titanic.csv'}]}, response_metadata={}, id='76ccb871-c5f2-4e46-9d1a-ca98ac3cd592'), AIMessage(content="我已经收到您的数据文件，我需要查看文件内容以对数据集有一个初步的了解。首先我会读取数据到 `df` 变量中，并通过 `df.info` 查
看 NaN 情况和数据类型。\n```python\n# Load the data into a DataFrame\ndf = read_df('titanic.csv')\n\n# Remove leading and trailing whitespaces in column names\ndf.columns = df.columns.str.strip()\n\n# Remove rows and columns that contain only empty values\ndf = df.dropna(how='all').dropna(axis=1, 
how='all')\n\n# Get the basic information of the dataset\ndf.info(memory_usage=False)\n```", additional_kwargs={'parent_id': 'some-parent-id1', 'thought': '我已经收到您的数据文件，我需要查看文件内容以对数据集有一个初步的了解。首先我会读取数据到 `df` 变量中，并通过 `df.info` 查看 NaN 情况和数据类型
。', 'action': {'tool': 'python', 'tool_input': "# Load the data into a DataFrame\ndf = read_df('titanic.csv')\n\n# Remove leading and trailing whitespaces in column names\ndf.columns = df.columns.str.strip()\n\n# Remove rows and columns that contain only empty values\ndf = df.dropna(how='all').dropna(axis=1, how='all')\n\n# Get the basic information of the dataset\ndf.info(memory_usage=False)"}, 'model_type': None}, response_metadata={}, id='7ee47c20-39b8-4520-ae94-813f6d987ab2', tool_calls=[{'name': 'python', 'args': {'query': "# Load the data into a DataFrame\ndf = read_df('titanic.csv')\n\n# Remove leading and trailing whitespaces in column names\ndf.columns = df.columns.str.strip()\n\n# Remove rows and columns that contain only empty values\ndf = df.dropna(how='all').dropna(axis=1, how='all')\n\n# Get the basic information of the dataset\ndf.info(memory_usage=False)"}, 'id': 'b937449b-515a-4d86-a287-03f5ce9cfe07', 'type': 'tool_call'}]), ToolMessage(content=[{'type': 'text', 'text': "```pycon\n---------------------------------------------------------------------------\nNameError                                 Traceback (most recent call last)\nCell In[1], line 2\n    
  1 # Load the data into a DataFrame\n----> 2 df = read_df('titanic.csv')\n      4 # Remove leading and trailing whitespaces in column names\n      5 df.columns = df.columns.str.strip()\n\nNameError: name 'read_df' is not defined\n```"}], name='python', id='af6b41a0-d587-4bde-bffb-db08380592e1', tool_call_id='b937449b-515a-4d86-a287-03f5ce9cfe07', artifact=[]), AIMessage(content='接下来我将用 `df.head(5)` 来查看数据集的前 5 行。\n```python\n# 
Show the first 5 rows to understand the structure\ndf.head(5)\n```', additional_kwargs={'parent_id': 'some-parent-id1', 'thought': '接下来我将用 `df.head(5)` 来查看数据集的前 5 行。', 'action': {'tool': 'python', 'tool_input': '# Show the first 5 rows to understand the structure\ndf.head(5)'}, 'model_type': None}, response_metadata={}, id='2d3fe296-6608-426d-bb7d-b77c15e45e1f', tool_calls=[{'name': 'python', 'args': {'query': '# Show the first 5 rows to understand the structure\ndf.head(5)'}, 'id': 'a65276f8-a8a7-4ac0-9315-2608f5f224ed', 'type': 'tool_call'}]), ToolMessage(content=[{'type': 'text', 'text': "```pycon\n---------------------------------------------------------------------------\nNameError                                 Traceback (most recent call last)\nCell In[2], line 2\n      1 # Show the first 5 rows to understand the structure\n----> 2 df.head(5)\n\nNameError: name 'df' is not defined\n```"}], name='python', id='da576eef-c0f7-43be-8a83-708be69330dc', tool_call_id='a65276f8-a8a7-4ac0-9315-2608f5f224ed', artifact=[]), AIMessage(content='我已经了解了数据集 titanic.csv 的基本信息。请问我可以帮您做些什么？', additional_kwargs={'parent_id': 'some-parent-id1'}, response_metadata={}, id='b570d3f4-46ac-4ae8-8dc8-1c3c61ee341f')]

问题是：
下面接着问的话题：How many men survived?
报错：openai.BadRequestError: Error code: 400 - {'object': 'error', 'message': 'As of transformers v4.44, default chat template is no longer allowed, so you must provide a chat template if the tokenizer does not define one.', 'type': 'BadRequestError', 'param': None, 'code': 400}
During task with name 'agent' and id 'd904a0c9-fa14-807f-74f9-06d8d146e88f'
During task with name 'data_analyze_graph' and id 'e1ade1e4-616b-b126-cf4a-22b0fb1acfba'
[IPKernelApp] WARNING | Parent appears to have exited, shutting down.

## Expected behavior

复现官方示例！

**Comment by vegetablest** [comment]
你好，我注意到你在使用agent进行数据预处理的时候pybox的kernel返回`NameError`，经过格式化之后错误如下:
```pycon
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[1], line 2
     1 # Load the data into a DataFrame
----> 2 df = read_df('titanic.csv')
      4 # Remove leading and trailing whitespaces in column names
      5 df.columns = df.columns.str.strip()

NameError: name 'read_df' is not defined
```
`read_df`是我们内置的一个用于加载数据的函数，在本地运行agent的时候需要通过`pip install -U tablegpt-agent[local]`安装`tablegpt-agent`,此时会将此函数安装到本地环境中的DEFAULT_TABLEGPT_IPYKERNEL_PROFILE_DIR目录下。出现此错误可以排查是否则正确的安装`tablegpt-agent[local]`，如果确实安装了local你可以通过打印DEFAULT_TABLEGPT_IPYKERNEL_PROFILE_DIR，然后查看是对应目录下否存在`read_df`函数。

**Comment by 851780266** [comment]
您的邮件已收到！

**Comment by 851780266** [comment]
> 你好，我注意到你在使用agent进行数据预处理的时候pybox的kernel返回`NameError`，经过格式化之后错误如下:
> 
> ```
> ---------------------------------------------------------------------------
> NameError                                 Traceback (most recent call last)
> Cell In[1], line 2
>      1 # Load the data into a DataFrame
> ----> 2 df = read_df('titanic.csv')
>       4 # Remove leading and trailing whitespaces in column names
>       5 df.columns = df.columns.str.strip()
> 
> NameError: name 'read_df' is not defined
> ```
> 
> `read_df`是我们内置的一个用于加载数据的函数，在本地运行agent的时候需要通过`pip install -U tablegpt-agent[local]`安装`tablegpt-agent`,此时会将此函数安装到本地环境中的DEFAULT_TABLEGPT_IPYKERNEL_PROFILE_DIR目录下。出现此错误可以排查是否则正确的安装`tablegpt-agent[local]`，如果确实安装了local你可以通过打印DEFAULT_TABLEGPT_IPYKERNEL_PROFILE_DIR，然后查看是对应目录下否存在`read_df`函数。

**Comment by 851780266** [comment]
我在模型的环境里运行后，提交文件的部分看起来是没问题了，保存依然没有变化
```
[HumanMessage(content='', additional_kwargs={'attachments': [{'filename': 'titanic.csv'}]}, response_metadata={}, id='67016297-3f1f-4bd1-9f25-6c6a29c8f716'), AIMessage(content="我已经收到您的数据文件，我需要查看文件内容以对数据集有一个初步的了解。首先我会读取数据到 `df` 变量中，并通过 `df.info` 查看 NaN 情况和数据类型。\n```python\n# Load the data into a DataFrame\ndf = read_df('titanic.csv')\n\n# Remove leading and trailing whitespaces in column names\ndf.columns = df.columns.str.strip()\n\n# Remove rows and columns that contain only empty values\ndf = df.dropna(how='all').dropna(axis=1, how='all')\n\n# Get the basic information of the dataset\ndf.info(memory_usage=False)\n```", additional_kwargs={'parent_id': 'some-parent-id1', 'thought': '我已经收到您的数据文件，我需要查看文件内容以对数据集有一个初步的了解。首先我会读取数据到 `df` 变量中，并通过 `df.info` 查看 NaN 情况和数据类型。', 'action': {'tool': 'python', 'tool_input': "# Load the data into a DataFrame\ndf = read_df('titanic.csv')\n\n# Remove leading and trailing whitespaces in column names\ndf.columns = df.columns.str.strip()\n\n# Remove rows and columns that contain only empty values\ndf = df.dropna(how='all').dropna(axis=1, how='all')\n\n# Get the basic information of the dataset\ndf.info(memory_usage=False)"}, 'model_type': None}, response_metadata={}, id='046964bc-75db-4832-aa4b-f28eaa2d595a', tool_calls=[{'name': 'python', 'args': {'query': "# Load the data into a DataFrame\ndf = read_df('titanic.csv')\n\n# Remove leading and trailing whitespaces in column names\ndf.columns = df.columns.str.strip()\n\n# Remove rows and columns that contain only empty values\ndf = df.dropna(how='all').dropna(axis=1, how='all')\n\n# Get the basic information of the dataset\ndf.info(memory_usage=False)"}, 'id': 'd0fcc21a-236b-45dd-a95e-b367bb0cd2e2', 'type': 'tool_call'}]), ToolMessage(content=[{'type': 'text', 'text': "```pycon\n<class 'pandas.core.frame.DataFrame'>\nRangeIndex: 4 entries, 0 to 3\nData columns (total 8 columns):\n #   Column    Non-Null Count  Dtype  \n---  ------    --------------  -----  \n 0   Pclass    4 non-null      int64  \n 1   Sex       4 non-null      object \n 2   Age       4 non-null      float64\n 3   SibSp     4 non-null      int64  \n 4   Parch     4 non-null      int64  \n 5   Fare      4 non-null      float64\n 6   Embarked  4 non-null      object \n 7   Survived  4 non-null      int64  \ndtypes: float64(2), int64(4), object(2)\n```"}], name='python', id='8c85d74a-3613-4bdc-9b8f-6ebe2cb03743', tool_call_id='d0fcc21a-236b-45dd-a95e-b367bb0cd2e2', artifact=[]), AIMessage(content='接下来我将用 `df.head(5)` 来查看数据集的前 5 行。\n```python\n# Show the first 5 rows to understand the structure\ndf.head(5)\n```', additional_kwargs={'parent_id': 'some-parent-id1', 'thought': '接下来我将用 `df.head(5)` 来查看数据集的前 5 行。', 'action': {'tool': 'python', 'tool_input': '# Show the first 5 rows to understand the structure\ndf.head(5)'}, 'model_type': None}, response_metadata={}, id='553b1e9f-b2ed-4def-9e77-8692bf8bc219', tool_calls=[{'name': 'python', 'args': {'query': '# Show the first 5 rows to understand the structure\ndf.head(5)'}, 'id': 'b0c7ee2e-3f7a-4e21-a252-4f5a21429346', 'type': 'tool_call'}]), ToolMessage(content=[{'type': 'text', 'text': '```pycon\n   Pclass     Sex   Age  SibSp  Parch    Fare Embarked  Survived\n0       2  female  29.0      0      2  23.000        S         1\n1       3  female  39.0      1      5  31.275        S         0\n2       3    male  26.5      0      0   7.225        C         0\n3       3    male  32.0      0      0  56.496        S         1\n```'}], name='python', id='be0d142a-f4b1-4059-8bca-07484fe4b010', tool_call_id='b0c7ee2e-3f7a-4e21-a252-4f5a21429346', artifact=[]), AIMessage(content='我已经了解了数据集 titanic.csv 的基本信息。请问我可以帮您做些什么？', additional_kwargs={'parent_id': 'some-parent-id1'}, response_metadata={}, id='5b16c15d-9c53-4b55-97da-af87213465da')]
```

后面的问答报错：
```
openai.BadRequestError: Error code: 400 - {'object': 'error', 'message': 'As of transformers v4.44, default chat template is no longer allowed, so you must provide a chat template if the tokenizer does not define one.', 'type': 'BadRequestError', 'param': None, 'code': 400}
```

**Comment by edwardzjl** [comment]
这看起来是 vllm 服务部署的问题，你能提供一下 `tokenizer_config.json` 的内容吗？

**Comment by 851780266** [comment]
我查了下vllm的资料，是不是需要配置聊天模版：
```
vllm serve <model> --chat-template ./template_dse_qwen2_vl.jinja
```
我在vlllm的git里下载了template_dse_qwen2_vl.jinja模版，启动时加上了--chat-template参数，没有报错了，但是没有打印答案（开头打印了DEFAULT_TABLEGPT_IPYKERNEL_PROFILE_DIR，结尾打印的是对象human_message）：
```
/root/miniconda3/envs/vllm/share/ipykernel/profile/tablegpt
[HumanMessage(content='', additional_kwargs={'attachments': [{'filename': 'titanic.csv'}]}, response_metadata={}, id='5f9fc936-114f-4312-92d3-34370cf0d046'), AIMessage(content="我已经收到您的数据文件，我需要查看文件内容以对数据集有一个初步的了解。首先我会读取数据到 `df` 变量中，并通过 `df.info` 查看 NaN 情况和数据类型。\n```python\n# Load the data into a DataFrame\ndf = read_df('titanic.csv')\n\n# Remove leading and trailing whitespaces in column names\ndf.columns = df.columns.str.strip()\n\n# Remove rows and columns that contain only empty values\ndf = df.dropna(how='all').dropna(axis=1, how='all')\n\n# Get the basic information of the dataset\ndf.info(memory_usage=False)\n```", additional_kwargs={'parent_id': 'some-parent-id1', 'thought': '我已经收到您的数据文件，我需要查看文件内容以对数据集有一个初步的了解。首先我会读取数据到 `df` 变量中，并通过 `df.info` 查看 NaN 情况和数据类型。', 'action': {'tool': 'python', 'tool_input': "# Load the data into a DataFrame\ndf = read_df('titanic.csv')\n\n# Remove leading and trailing whitespaces in column names\ndf.columns = df.columns.str.strip()\n\n# Remove rows and columns that contain only empty values\ndf = df.dropna(how='all').dropna(axis=1, how='all')\n\n# Get the basic information of the dataset\ndf.info(memory_usage=False)"}, 'model_type': None}, response_metadata={}, id='f80a30fe-5600-40c3-8729-3cc5b7da52b4', tool_calls=[{'name': 'python', 'args': {'query': "# Load the data into a DataFrame\ndf = read_df('titanic.csv')\n\n# Remove leading and trailing whitespaces in column names\ndf.columns = df.columns.str.strip()\n\n# Remove rows and columns that contain only empty values\ndf = df.dropna(how='all').dropna(axis=1, how='all')\n\n# Get the basic information of the dataset\ndf.info(memory_usage=False)"}, 'id': '31c900ad-ddf8-42f3-a805-dce577df5e88', 'type': 'tool_call'}]), ToolMessage(content=[{'type': 'text', 'text': "```pycon\n<class 'pandas.core.frame.DataFrame'>\nRangeIndex: 4 entries, 0 to 3\nData columns (total 8 columns):\n #   Column    Non-Null Count  Dtype  \n---  ------    --------------  -----  \n 0   Pclass    4 non-null      int64  \n 1   Sex       4 non-null      object \n 2   Age       4 non-null      float64\n 3   SibSp     4 non-null      int64  \n 4   Parch     4 non-null      int64  \n 5   Fare      4 non-null      float64\n 6   Embarked  4 non-null      object \n 7   Survived  4 non-null      int64  \ndtypes: float64(2), int64(4), object(2)\n```"}], name='python', id='7e503c0a-bc02-4c5e-a830-b4538e0f4ac0', tool_call_id='31c900ad-ddf8-42f3-a805-dce577df5e88', artifact=[]), AIMessage(content='接下来我将用 `df.head(5)` 来查看数据集的前 5 行。\n```python\n# Show the first 5 rows to understand the structure\ndf.head(5)\n```', additional_kwargs={'parent_id': 'some-parent-id1', 'thought': '接下来我将用 `df.head(5)` 来查看数据集的前 5 行。', 'action': {'tool': 'python', 'tool_input': '# Show the first 5 rows to understand the structure\ndf.head(5)'}, 'model_type': None}, response_metadata={}, id='7f3904f9-3dc3-4a5f-85c9-c7c21a150445', tool_calls=[{'name': 'python', 'args': {'query': '# Show the first 5 rows to understand the structure\ndf.head(5)'}, 'id': '12424793-07cc-49c4-b473-9266c5278526', 'type': 'tool_call'}]), ToolMessage(content=[{'type': 'text', 'text': '```pycon\n   Pclass     Sex   Age  SibSp  Parch    Fare Embarked  Survived\n0       2  female  29.0      0      2  23.000        S         1\n1       3  female  39.0      1      5  31.275        S         0\n2       3    male  26.5      0      0   7.225        C         0\n3       3    male  32.0      0      0  56.496        S         1\n```'}], name='python', id='2110bb72-4d15-4d7f-a3a4-6e2fd97c6a71', tool_call_id='12424793-07cc-49c4-b473-9266c5278526', artifact=[]), AIMessage(content='我已经了解了数据集 titanic.csv 的基本信息。请问我可以帮您做些什么？', additional_kwargs={'parent_id': 'some-parent-id1'}, response_metadata={}, id='c102fb5b-048d-40de-bc8e-702e91ac19a0')]
content='How many men survived?' additional_kwargs={} response_metadata={}
```

另：我的启动命令是通过--served-model-name TableGPT2-7B，没有加载本地模型文件，没有找到tokenizer_config.json

**Comment by edwardzjl** [comment]
> 我查了下vllm的资料，是不是需要配置聊天模版：
> 
> ```
> vllm serve <model> --chat-template ./template_dse_qwen2_vl.jinja
> ```
> 
> 我在vlllm的git里下载了template_dse_qwen2_vl.jinja模版，启动时加上了--chat-template参数，没有报错了，但是没有打印答案（开头打印了DEFAULT_TABLEGPT_IPYKERNEL_PROFILE_DIR，结尾打印的是对象human_message）：
> 
> ```
> /root/miniconda3/envs/vllm/share/ipykernel/profile/tablegpt
> [HumanMessage(content='', additional_kwargs={'attachments': [{'filename': 'titanic.csv'}]}, response_metadata={}, id='5f9fc936-114f-4312-92d3-34370cf0d046'), AIMessage(content="我已经收到您的数据文件，我需要查看文件内容以对数据集有一个初步的了解。首先我会读取数据到 `df` 变量中，并通过 `df.info` 查看 NaN 情况和数据类型。\n```python\n# Load the data into a DataFrame\ndf = read_df('titanic.csv')\n\n# Remove leading and trailing whitespaces in column names\ndf.columns = df.columns.str.strip()\n\n# Remove rows and columns that contain only empty values\ndf = df.dropna(how='all').dropna(axis=1, how='all')\n\n# Get the basic information of the dataset\ndf.info(memory_usage=False)\n```", additional_kwargs={'parent_id': 'some-parent-id1', 'thought': '我已经收到您的数据文件，我需要查看文件内容以对数据集有一个初步的了解。首先我会读取数据到 `df` 变量中，并通过 `df.info` 查看 NaN 情况和数据类型。', 'action': {'tool': 'python', 'tool_input': "# Load the data into a DataFrame\ndf = read_df('titanic.csv')\n\n# Remove leading and trailing whitespaces in column names\ndf.columns = df.columns.str.strip()\n\n# Remove rows and columns that contain only empty values\ndf = df.dropna(how='all').dropna(axis=1, how='all')\n\n# Get the basic information of the dataset\ndf.info(memory_usage=False)"}, 'model_type': None}, response_metadata={}, id='f80a30fe-5600-40c3-8729-3cc5b7da52b4', tool_calls=[{'name': 'python', 'args': {'query': "# Load the data into a DataFrame\ndf = read_df('titanic.csv')\n\n# Remove leading and trailing whitespaces in column names\ndf.columns = df.columns.str.strip()\n\n# Remove rows and columns that contain only empty values\ndf = df.dropna(how='all').dropna(axis=1, how='all')\n\n# Get the basic information of the dataset\ndf.info(memory_usage=False)"}, 'id': '31c900ad-ddf8-42f3-a805-dce577df5e88', 'type': 'tool_call'}]), ToolMessage(content=[{'type': 'text', 'text': "```pycon\n<class 'pandas.core.frame.DataFrame'>\nRangeIndex: 4 entries, 0 to 3\nData columns (total 8 columns):\n #   Column    Non-Null Count  Dtype  \n---  ------    --------------  -----  \n 0   Pclass    4 non-null      int64  \n 1   Sex       4 non-null      object \n 2   Age       4 non-null      float64\n 3   SibSp     4 non-null      int64  \n 4   Parch     4 non-null      int64  \n 5   Fare      4 non-null      float64\n 6   Embarked  4 non-null      object \n 7   Survived  4 non-null      int64  \ndtypes: float64(2), int64(4), object(2)\n```"}], name='python', id='7e503c0a-bc02-4c5e-a830-b4538e0f4ac0', tool_call_id='31c900ad-ddf8-42f3-a805-dce577df5e88', artifact=[]), AIMessage(content='接下来我将用 `df.head(5)` 来查看数据集的前 5 行。\n```python\n# Show the first 5 rows to understand the structure\ndf.head(5)\n```', additional_kwargs={'parent_id': 'some-parent-id1', 'thought': '接下来我将用 `df.head(5)` 来查看数据集的前 5 行。', 'action': {'tool': 'python', 'tool_input': '# Show the first 5 rows to understand the structure\ndf.head(5)'}, 'model_type': None}, response_metadata={}, id='7f3904f9-3dc3-4a5f-85c9-c7c21a150445', tool_calls=[{'name': 'python', 'args': {'query': '# Show the first 5 rows to understand the structure\ndf.head(5)'}, 'id': '12424793-07cc-49c4-b473-9266c5278526', 'type': 'tool_call'}]), ToolMessage(content=[{'type': 'text', 'text': '```pycon\n   Pclass     Sex   Age  SibSp  Parch    Fare Embarked  Survived\n0       2  female  29.0      0      2  23.000        S         1\n1       3  female  39.0      1      5  31.275        S         0\n2       3    male  26.5      0      0   7.225        C         0\n3       3    male  32.0      0      0  56.496        S         1\n```'}], name='python', id='2110bb72-4d15-4d7f-a3a4-6e2fd97c6a71', tool_call_id='12424793-07cc-49c4-b473-9266c5278526', artifact=[]), AIMessage(content='我已经了解了数据集 titanic.csv 的基本信息。请问我可以帮您做些什么？', additional_kwargs={'parent_id': 'some-parent-id1'}, response_metadata={}, id='c102fb5b-048d-40de-bc8e-702e91ac19a0')]
> content='How many men survived?' additional_kwargs={} response_metadata={}
> ```

可能是模板不对，用的不是 qwen2_vl ，而是 qwen2.5 的，见 <https://huggingface.co/tablegpt/TableGPT2-7B/blob/main/tokenizer_config.json>

> 另：我的启动命令是通过--served-model-name TableGPT2-7B，没有加载本地模型文件，没有找到tokenizer_config.json

你可以看下你的 hf cache 目录，通常是 `~/.cache/huggingface`，找一下 `TableGPT2` 所在的目录，是否有下载 `tokenizer_config.json`，这个文件目前是必须的。

**Comment by 851780266** [comment]
我从huggingface上拉取的文件，tokenizer_config.json文件就是您推荐的，vllm开始加载后cuda oom了，我的服务器是nvidia-16G的，确认一下要求最低显存是多少的？
```
python -m vllm.entrypoints.openai.api_server --served-model-name TableGPT2-7B --port 8000 --trust-remote-code --gpu-memory-utilization 0.9 --model ./TableGPT2-7B --dtype=half
```

**Comment by edwardzjl** [comment]
权重需要大约是 15 GB 的缓存，16G oom 的话可能是默认的 context length 塞不下。你可以贴下 vllm 的启动报错日志。

**Comment by 851780266** [comment]
我是通过 python tablegpt-agent.py 运行的脚本文件，不是通过jupyter运行的，是不是与ipython内核ipykernel有关？

**Comment by 851780266** [comment]
上述已经是正常运行了，但是上述脚本的最后提问结果打印那里没有进去，导致结果没有打印出来，不知道是不是版本的问题。

**Comment by edwardzjl** [comment]
你可以打印出来所有的事件看看问题在哪:

```python
...
    async for event in agent.astream_events(
        input={
            # After using checkpoint, you only need to add new messages here.
            "messages": [human_message],
            "parent_id": "some-parent-id2",
            "date": date.today(),
        },
        version="v2",
        # We configure the same thread_id to use checkpoints to retrieve the memory of the last run.
        config={"configurable": {"thread_id": "some-thread-id"}},
    ):
        print(event)
```
