### ISSUE TITLE
About the 72B model

### ISSUE THREAD

**Issue by Foxyrep** [tablegpt/tablegpt-agent#65]
Thanks for your awesome work! 
BTW I've found the 7B model on huggingface, since you mentioned that you've fine-tuned another model which is 72B, in your article, I'm wondering when would you release it? 
Thanks

**Comment by jzhao2024** [comment]
guys, thanks for your interest!

unfortunately, we currently don't have a clear schedule on releasing the 72b model (not yet). it still has much room to be further optimized, and we'd work on that.

please stay posted. we appreciate it ;)
