### ISSUE TITLE
依赖环境

### ISSUE THREAD

**Issue by mosthandsomeman** [tablegpt/tablegpt-agent#70]
能否提供一个项目的requirements.txt?

**Comment by edwardzjl** [comment]
`tablegpt-agent` 使用 [hatch](https://github.com/pypa/hatch) 管理项目，依赖声明在 `pyproject.toml` 里

**Comment by mosthandsomeman** [comment]
作者您好，是否方便拉个微信交流群，方便大家交流？


1539954482
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tablegpt/tablegpt-agent"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月12日(星期二) 中午11:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tablegpt/tablegpt-agent] 依赖环境 (Issue #70)





 
tablegpt-agent 使用 hatch 管理项目，依赖声明在 pyproject.toml 里
