### ISSUE TITLE
本地跑Quick Start里的例子的时候报httpx.ResponseNotRead: Attempted to access streaming response content, without having called `read()`.

### ISSUE THREAD

**Issue by jianpugh** [tablegpt/tablegpt-agent#71]
![image](https://github.com/user-attachments/assets/ccf21457-30a7-4b78-b77b-16d5367902b9)
看起来像是用stream的时候没有调用read来获取response？

**Comment by edwardzjl** [comment]
能否提供一下您跑例子的环境信息，包括代码片段？

**Comment by jianpugh** [comment]
环境就是本地pycharm，然后在服务器上容器里用vllm启动的推理服务，postman是可以通的，代码用的就是简单地那个示例`import asyncio
from datetime import date

from langchain_core.messages import HumanMessage
from langchain_openai import ChatOpenAI
from pybox import LocalPyBoxManager
from tablegpt.agent import create_tablegpt_graph


# tablegpt-agent fully supports async invocation
async def main() -> None:
    llm = ChatOpenAI(base_url="http://7.216.53.54:6680/v1", api_key="TableGPT2-7B_api_key", model_name="TableGPT2-7B")
    
    # Use local pybox manager for development and testing
    pybox_manager = LocalPyBoxManager()

    agent = create_tablegpt_graph(
        llm=llm,
        pybox_manager=pybox_manager,
    )

    message = HumanMessage(content="Hi")
    _input = {
        "messages": [message],
        "parent_id": "some-parent-id",
        "date": date.today(),  # noqa: DTZ011
    }

    async for event in agent.astream_events(
        input=_input,
        version="v2",
    ):
        print(event)  # noqa: T201


asyncio.run(main())`

我之前试了下，用openai真实的key是可以调通的，不知道本地用vllm启服务为啥不可以

**Comment by vegetablest** [comment]
你好，能提供一下容器内vllm服务的日志吗

**Comment by edwardzjl** [comment]
可否提供一下服务器上 vllm 服务的启动参数？

**Comment by jianpugh** [comment]
vllm启动参数如下
python -m vllm.entrypoints.openai.api_server --served-model-name TableGPT2-7B --model /kos_ulan/jianpu/llm/model/bare_model/TableGPT2-7B/ --port=6680

**Comment by jianpugh** [comment]
> 你好，能提供一下容器内vllm服务的日志吗

[vllm_log.txt](https://github.com/user-attachments/files/17712732/vllm_log.txt)
vllm服务日志如上

**Comment by jianpugh** [comment]
打扰了，应该是我本地网络的问题

**Comment by edwardzjl** [comment]
好的，issue 我先关闭了，有问题随时回来。
