### ISSUE TITLE
能不能够直接输入图或者表格的图像以进行图表问答？

### ISSUE THREAD

**Issue by LIN-SHANG** [tablegpt/tablegpt-agent#72]

**Comment by marmeteor** [comment]
我也想问，看起来好像在agent中指定vlm就可以实现，不知道作者能不能提供一个好的vlm

**Comment by edwardzjl** [comment]
目前还不支持对图片直接进行问答，主要考虑到图片内容过于宽泛，用户上传的图片不一定包含表格内容，或者包含不规则的表格、多个表格等
可以考虑在前面加上一个 OCR 模块，但是也要考虑 OCR 的准确性等问题

**Comment by edwardzjl** [comment]
@marmeteor `tablegpt-agent` 中的 VLM 是用于对 tool 的 output 进行解读，无法直接解读 input

**Comment by marmeteor** [comment]
> @marmeteor `tablegpt-agent` 中的 VLM 是用于对 tool 的 output 进行解读，无法直接解读 input

请问您使用的是什么VLM呢？论文中没有提到
