### ISSUE TITLE
本地运行quick start回复全是感叹号

### ISSUE THREAD

**Issue by thunder95** [tablegpt/tablegpt-agent#82]
安装好相应的依赖环境后，本地运行7B模型，跑quick start例子，返回的内容全是感叹号。且不能正常终止。
{'event': 'on_chat_model_stream', 'data': {'chunk': AIMessageChunk(content='!', additional_kwargs={}, response_metadata={}, id='run-5e40620c-bb38-442d-a45f-eb8eda544a17')}

**Comment by edwardzjl** [comment]
请问用的是什么模型？vllm 启动参数是什么？

**Comment by thunder95** [comment]
@edwardzjl 感谢回复， 启动尝试了vllm serve命令行, 也尝试了python启动的命令，如： python -m vllm.entrypoints.openai.api_server --served-model-name TableGPT2-7B --model tablegpt2/ --port 6680， vllm版本是vllm                              0.6.3.dev188+gf519902c.cu118.

**Comment by thunder95** [comment]
打扰了，可能下载的模型有问题，用modelscope就正常了。
