### ISSUE TITLE
带有合并单元格的复杂表格应该以什么格式输入和输出？

### ISSUE THREAD

**Issue by MZS0514** [tablegpt/tablegpt-agent#90]

**Comment by Sherryran08** [comment]
请问作者目前支持什么格式的表格输入，可以支持markdown、html格式的表格输入吗

**Comment by vegetablest** [comment]
@MZS0514 带有合并单元格的复杂表格与普通表格的输入方式相同，其文件格式（如 `.xls`、`.xlsx`）应根据具体文件类型选择。不过，合并单元格等不规则数据可能会增加处理难度。为提升处理效果，可以使用 [Dataset Normalizer 插件](https://tablegpt.github.io/tablegpt-agent/howto/normalize-datasets) 来优化数据预处理能力，使 Agent 更擅长应对不规则数据。  

以下资源可能对你有帮助：  
1. https://tablegpt.github.io/tablegpt-agent/howto/normalize-datasets
2. https://github.com/tablegpt/tablegpt-agent/issues/124

**Comment by vegetablest** [comment]
@Sherryran08 目前主要支持 CSV 文件和 Excel 文件格式，以及相关变种，如 `.csv`、`.tsv`、`.xls`、`.xlsx`、`.xlsm`、`.xlsb`、`.odf`、`.ods` 和 `.odt`。暂不支持 Markdown 或 HTML 格式的表格输入。

**Comment by jianpugh** [comment]
> @MZS0514 带有合并单元格的复杂表格与普通表格的输入方式相同，其文件格式（如 `.xls`、`.xlsx`）应根据具体文件类型选择。不过，合并单元格等不规则数据可能会增加处理难度。为提升处理效果，可以使用 [Dataset Normalizer 插件](https://tablegpt.github.io/tablegpt-agent/howto/normalize-datasets) 来优化数据预处理能力，使 Agent 更擅长应对不规则数据。
> 
> 以下资源可能对你有帮助：
> 
> 1. https://tablegpt.github.io/tablegpt-agent/howto/normalize-datasets
> 2. [测试产品生成统计表.xlsx，agent无法正确提取表头 #124](https://github.com/tablegpt/tablegpt-agent/issues/124)

https://github.com/tablegpt/tablegpt-agent/issues/124#issuecomment-2540862269
我在一个已关闭的issue提问了下，尝试了normalize，但好像没生效，辛苦帮忙看看

**Comment by edwardzjl** [comment]
@jianpugh 抱歉没有及时回复，麻烦你把那个评论创建成一个新的 issue。
