### ISSUE TITLE
[IPKernelApp] WARNING | Parent appears to have exited, shutting down.

### ISSUE THREAD

**Issue by JACKYLUO1991** [tablegpt/tablegpt-agent#91]
数据分析自己上传的csv表格，显示[IPKernelApp] WARNING | Parent appears to have exited, shutting down. 等待状态    请问如何解决呢？

**Comment by JACKYLUO1991** [comment]
![image](https://github.com/user-attachments/assets/ecaf3af9-8055-464a-9271-248ffd171664)
后面貌似还截断了...

**Comment by JACKYLUO1991** [comment]
![image](https://github.com/user-attachments/assets/a0eefc46-411f-4c80-a787-5f4c06b043ff)
后面内容貌似还截断了。。。

**Comment by edwardzjl** [comment]
这个只是退出时候的一个 message，并不是 bug
具体原因是我们在 quickstart 的时候没有清理 IPython kernel，然后主程序就跑完了。相当于 IPython 的父进程退出了，IPython 就报了这个 warning

https://github.com/OpenInterpreter/open-interpreter/issues/1125#issuecomment-2024082462 和 https://github.com/OpenInterpreter/open-interpreter/pull/1145 也是类似的情况

**Comment by JACKYLUO1991** [comment]
@edwardzjl 感谢您的回复，这个问题我就关闭了...
