### ISSUE TITLE
titanic例子中，read_df执行错误

### ISSUE THREAD

**Issue by rayallen28** [tablegpt/tablegpt-agent#98]
![无标题](https://github.com/user-attachments/assets/4d334d6c-66db-4843-8a7b-94e7973515eb)
不懂，这里硬编码的read_df，在pybox中执行是失败的。pandas库中dataframe没有这个read_df方法，怎么才能成功执行？求大佬指点。

**Comment by rayallen28** [comment]
![Uploading 无标题.png…]()

**Comment by vegetablest** [comment]
read_df是我们在ipython kernel中内置的一个用户自定义函数，当你本地运行的时候通过`pip install tablegpt-agent[local]`的时候我们已经将自定义函数放到了共享目录中，你创建pybox_manager的时候指定一下profile_dir就行。
```python
from tablegpt import DEFAULT_TABLEGPT_IPYKERNEL_PROFILE_DIR

pybox_manager = LocalPyBoxManager(profile_dir=DEFAULT_TABLEGPT_IPYKERNEL_PROFILE_DIR)
```
如果你想增加更多的自定义函数可以参考 https://github.com/tablegpt/ipy-kernel/blob/main/README-zh.md

**Comment by Wonderland23** [comment]
> ![无标题](https://private-user-images.githubusercontent.com/95999234/387204949-4d334d6c-66db-4843-8a7b-94e7973515eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MjEwNzEsIm5iZiI6MTczNDQyMDc3MSwicGF0aCI6Ii85NTk5OTIzNC8zODcyMDQ5NDktNGQzMzRkNmMtNjZkYi00ODQzLThhN2ItOTRlNzk3MzUxNWViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDA3MzI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkYzdiZDIzMzYyNjg1YjAwNzYwNmJiOTJkNzQwNjVhOTk1NWQ4ZDlhNWYwMjI5ODRlOTE3YTQyZDAxNzk5NzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5nKrGrbwZzOgLCPJhKvtMWOq2vHVxYo12q-9mhgHi3I) 不懂，这里硬编码的read_df，在pybox中执行是失败的。pandas库中dataframe没有这个read_df方法，怎么才能成功执行？求大佬指点。

麻烦问下这个可视化界面是自带的吗？为何我用vllm启动后访问localhost显示为not found？感谢！
![image](https://github.com/user-attachments/assets/98e2ba08-36f7-42bc-ac07-67d3b9a47f8b)
![image](https://github.com/user-attachments/assets/7919473c-9d1c-4407-82e2-f2fb29dd2088)

**Comment by edwardzjl** [comment]
> > ![无标题](https://private-user-images.githubusercontent.com/95999234/387204949-4d334d6c-66db-4843-8a7b-94e7973515eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MjEwNzEsIm5iZiI6MTczNDQyMDc3MSwicGF0aCI6Ii85NTk5OTIzNC8zODcyMDQ5NDktNGQzMzRkNmMtNjZkYi00ODQzLThhN2ItOTRlNzk3MzUxNWViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDA3MzI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkYzdiZDIzMzYyNjg1YjAwNzYwNmJiOTJkNzQwNjVhOTk1NWQ4ZDlhNWYwMjI5ODRlOTE3YTQyZDAxNzk5NzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5nKrGrbwZzOgLCPJhKvtMWOq2vHVxYo12q-9mhgHi3I) 不懂，这里硬编码的read_df，在pybox中执行是失败的。pandas库中dataframe没有这个read_df方法，怎么才能成功执行？求大佬指点。
> 
> 麻烦问下这个可视化界面是自带的吗？为何我用vllm启动后访问localhost显示为not found？感谢！ ![image](https://private-user-images.githubusercontent.com/36074449/396398376-98e2ba08-36f7-42bc-ac07-67d3b9a47f8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MjE2NDEsIm5iZiI6MTczNDQyMTM0MSwicGF0aCI6Ii8zNjA3NDQ0OS8zOTYzOTgzNzYtOThlMmJhMDgtMzZmNy00MmJjLWFjMDctNjdkM2I5YTQ3ZjhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDA3NDIyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1ZDIzMmQ5NDE2Y2UwZTM0MDQwZGE3ZTAyNWU0NDA0YjE3NjM5OTNmNWVmMTU4NzBlZDhlOWQxMzE3ZTFmMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RuNajZS2bgTYJtI-m-NLMpefCopQyKpVMCuBx2iE2ek) ![image](https://private-user-images.githubusercontent.com/36074449/396398528-7919473c-9d1c-4407-82e2-f2fb29dd2088.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MjE2NDEsIm5iZiI6MTczNDQyMTM0MSwicGF0aCI6Ii8zNjA3NDQ0OS8zOTYzOTg1MjgtNzkxOTQ3M2MtOWQxYy00NDA3LTgyZTItZjJmYjI5ZGQyMDg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDA3NDIyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjMWI2NDlhMDAwZDc2OTM1Yzk1NDU3NTVlZTVlMWZmZjY1YWRjMmRlMjE4MDkwZTgyNWNlYWJjODBhYjEyNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TbyTJS3RsYNBjE6vvolX3SuCI7_8fUBHxgM4cEme31I)

关于 vllm 启动 apiserver 的服务可以参考 [vllm 官方文档](https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html).

如果还是有问题的话，请新建一个 issue 或是 discussion.

**Comment by Wonderland23** [comment]
> > > ![无标题](https://private-user-images.githubusercontent.com/95999234/387204949-4d334d6c-66db-4843-8a7b-94e7973515eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MjEwNzEsIm5iZiI6MTczNDQyMDc3MSwicGF0aCI6Ii85NTk5OTIzNC8zODcyMDQ5NDktNGQzMzRkNmMtNjZkYi00ODQzLThhN2ItOTRlNzk3MzUxNWViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDA3MzI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkYzdiZDIzMzYyNjg1YjAwNzYwNmJiOTJkNzQwNjVhOTk1NWQ4ZDlhNWYwMjI5ODRlOTE3YTQyZDAxNzk5NzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5nKrGrbwZzOgLCPJhKvtMWOq2vHVxYo12q-9mhgHi3I) 不懂，这里硬编码的read_df，在pybox中执行是失败的。pandas库中dataframe没有这个read_df方法，怎么才能成功执行？求大佬指点。
> > 
> > 
> > 麻烦问下这个可视化界面是自带的吗？为何我用vllm启动后访问localhost显示为not found？感谢！ ![image](https://private-user-images.githubusercontent.com/36074449/396398376-98e2ba08-36f7-42bc-ac07-67d3b9a47f8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MjE2NDEsIm5iZiI6MTczNDQyMTM0MSwicGF0aCI6Ii8zNjA3NDQ0OS8zOTYzOTgzNzYtOThlMmJhMDgtMzZmNy00MmJjLWFjMDctNjdkM2I5YTQ3ZjhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDA3NDIyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1ZDIzMmQ5NDE2Y2UwZTM0MDQwZGE3ZTAyNWU0NDA0YjE3NjM5OTNmNWVmMTU4NzBlZDhlOWQxMzE3ZTFmMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RuNajZS2bgTYJtI-m-NLMpefCopQyKpVMCuBx2iE2ek) ![image](https://private-user-images.githubusercontent.com/36074449/396398528-7919473c-9d1c-4407-82e2-f2fb29dd2088.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MjE2NDEsIm5iZiI6MTczNDQyMTM0MSwicGF0aCI6Ii8zNjA3NDQ0OS8zOTYzOTg1MjgtNzkxOTQ3M2MtOWQxYy00NDA3LTgyZTItZjJmYjI5ZGQyMDg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDA3NDIyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjMWI2NDlhMDAwZDc2OTM1Yzk1NDU3NTVlZTVlMWZmZjY1YWRjMmRlMjE4MDkwZTgyNWNlYWJjODBhYjEyNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TbyTJS3RsYNBjE6vvolX3SuCI7_8fUBHxgM4cEme31I)
> 
> 关于 vllm 启动 apiserver 的服务可以参考 [vllm 官方文档](https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html).
> 
> 如果还是有问题的话，请新建一个 issue 或是 discussion.

感谢帮助，如有问题会新开issue
